apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: kub-poc-control-plane
  namespace: tink-system
spec:
  kubeadmConfigSpec:
    format: ignition
    ignition:
      containerLinuxConfig:
        additionalConfig: |
          storage:
            links:
              - path: /etc/extensions/kubernetes.raw
                hard: false
                target: /opt/extensions/kubernetes/kubernetes-v1.30.0-x86-64.raw
            files:
              - path: /etc/sysupdate.kubernetes.d/kubernetes-v1.30.conf
                mode: 0644
                contents:
                  remote:
                    url: https://github.com/flatcar/sysext-bakery/releases/download/latest/kubernetes-v1.30.conf
              - path: /etc/sysupdate.d/noop.conf
                mode: 0644
                contents:
                  remote:
                    url: https://github.com/flatcar/sysext-bakery/releases/download/latest/noop.conf
              - path: /opt/extensions/kubernetes/kubernetes-v1.30.0-x86-64.raw
                contents:
                  remote:
                    url: https://github.com/flatcar/sysext-bakery/releases/download/latest/kubernetes-v1.30.0-x86-64.raw
          systemd:
            units:
              - name: systemd-sysupdate.service
                dropins:
                  - name: kubernetes.conf
                    contents: |
                      [Service]
                      ExecStartPre=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/kubernetes.raw > /tmp/kubernetes"
                      ExecStartPre=/usr/lib/systemd/systemd-sysupdate -C kubernetes update
                      ExecStartPost=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/kubernetes.raw > /tmp/kubernetes-new"
                      ExecStartPost=/usr/bin/sh -c "if ! cmp --silent /tmp/kubernetes /tmp/kubernetes-new; then touch /run/reboot-required; fi"
              - name: update-engine.service
                # Set this to 'false' if you want to enable Flatcar auto-update
                mask: false
              - name: locksmithd.service
                # NOTE: To coordinate the node reboot in this context, we recommend to use Kured.
                mask: true
              - name: systemd-sysupdate.timer
                # Set this to 'true' if you want to enable the Kubernetes auto-update.
                # NOTE: Only patches version will be pulled.
                enabled: false
              - name: kubeadm.service
                enabled: true
                dropins:
                  - name: 10-flatcar.conf
                    contents: |
                      [Unit]
                      Requires=containerd.service
                      After=containerd.service
    clusterConfiguration: {}
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: PROVIDER_ID
    joinConfiguration:
      nodeRegistration:
        ignorePreflightErrors:
          - DirAvailable--etc-kubernetes-manifests
        kubeletExtraArgs:
          provider-id: PROVIDER_ID
    preKubeadmCommands:
      - "until ping cloudbase.it -c 2 -t 100; do sleep 1; done && mkdir -p /etc/kubernetes/manifests && ctr images pull ghcr.io/kube-vip/kube-vip:v0.7.2 && ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.7.2 vip /kube-vip manifest pod --arp --interface $(ip -4 -j route list default | jq -r .[0].dev) --address 192.168.56.151 --controlplane --leaderElection > /etc/kubernetes/manifests/kube-vip.yaml"
      - "sed -i 's#path: /etc/kubernetes/admin.conf#path: /etc/kubernetes/super-admin.conf#' /etc/kubernetes/manifests/kube-vip.yaml"
    postKubeadmCommands:
      - "sed -i 's#path: /etc/kubernetes/super-admin.conf#path: /etc/kubernetes/admin.conf#' /etc/kubernetes/manifests/kube-vip.yaml"
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: TinkerbellMachineTemplate
      name: kub-poc-control-plane
  replicas: 1
  version: v1.30.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellMachineTemplate
metadata:
  name: kub-poc-control-plane
  namespace: tink-system
spec:
  template:
    spec:
      templateOverride: |
        version: "0.1"
        name: kub-poc-control-plane-flatcar-amd64
        global_timeout: 6000
        tasks:
          - name: "kub-poc-control-plane-flatcar"
            worker: "{{.device_1}}"
            volumes:
              - /dev:/dev
              - /dev/console:/dev/console
              - /lib/firmware:/lib/firmware:ro
              - /run:/run
            actions:
              - name: "stream-image"
                image: quay.io/tinkerbell-actions/image2disk:v1.0.0
                timeout: 600
                environment:
                  IMG_URL: http://192.168.56.1/flatcar_production_image.bin.bzip2
                  DEST_DISK: /dev/vda
                  COMPRESSED: true
              - name: "change-kernel-configuration"
                image: quay.io/tinkerbell-actions/writefile:v1.0.0
                timeout: 90
                environment:
                  DEST_DISK: /dev/vda6
                  FS_TYPE: btrfs
                  DEST_PATH: /grub.cfg
                  UID: 0
                  GID: 0
                  MODE: 0777
                  DIRMODE: 0755
                  CONTENTS: |
                    set linux_append="$linux_append flatcar.autologin=tty1 flatcar.config.url=http://192.168.56.130:50061/2009-04-04/user-data"
              - name: "reboot"
                image: tinkerbell.azurecr.io/tinkerbell/reboot:1.0
                timeout: 90
                volumes:
                  - /worker:/worker
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kub-poc
  namespace: tink-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.167.0.0/16
    services:
      cidrBlocks:
        - 172.26.0.0/16
  controlPlaneEndpoint:
    host: 192.168.56.151
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: kub-poc-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: TinkerbellCluster
    name: kub-poc
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellCluster
metadata:
  name: kub-poc
  namespace: tink-system
spec:
  imageLookupBaseRegistry: ""
