apiVersion: v1
kind: Service
metadata:
  name: fedora-public-ip
  labels:
    app.kubernetes.io/advertise: "true"
spec:
  ports:
  - port: 22
    targetPort: 22
  selector:
    special: fedora-vm
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: fedora-public-ip
  labels:
    special: fedora-vm
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
    resources:
      requests:
        memory: 1Gi
  volumes:
  - name: containerdisk
    containerDisk:
      image: quay.io/kubevirt/fedora-cloud-container-disk-demo:20210811_9fec1f849
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
