---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bm-auth-altra
  namespace: tink-system
spec:
  encryptedData:
    password: AgAM4RIonZ3qV5gyLfWnZ2yYkmxIRXAqqbVNUMpJ5huP7Kw65zD+NoQVJmoj6jVqcHr89oxMOiArJ4AF2vyXbHyzalguxwMdNsDAQ0K4p7bQ3Hm7ETX+e53B5eu5kOfjnQECT6jlETatyFyYo9hFateSC0N6SM1cxk7EpgGrFqjXJtHDunNk04GHIH688BzwiwkXRHn47raH7I1sQ01oiswExtsxFeFF8XZD2BtBRn2WUObdiDYwuAcsyf1BLwpPrrLA2uILbjP9Tn39677dfnZNbOHgnN5g4xObQ06tSqsJ0Z/+B3yOs4BL5j5xfwefqqGcg/jYo3TybvvMUIXjBTMApQ7swoHqtGYm72NJZ+Scruwmn4/8Ccqill/uBRG7f/qUJ8wuhnmZ6Ksn3YF5qbuzxk2ZIIx/83hRPGOdrpRfCrE08jRnThv6B1GzCCkoMit7vEQJZbLUQ3VnDELZpxMcqGAugmgMLqnn99r0APiSOoWjIFSdYTfElyXxCxPxuA490Bqnq/crviXoaZWwON/drrHAsZkjw2U0Hwq40O47DMd6SGlBfm9jPzxJEj0v774oJjimw1ufeMfTBw+f09+kKjENlhxM2geMNBeJkOC6dmt7S3qBTjc9uzcK3i76WTvAzZGUCJgwmQEnfAIyCeNppzk6pa+G7twDZxhXPHnud8+H0Ymis1z6i7YQSx4WxRNkgivm6A==
    username: AgAmL35eHmbmyUaQSDZnbkScmJlL/M5xf/XQ0Av2+Q/zcLvKTswVb6Bxz1J9jcy1uueWpFX3lFvoKzfYcGEp+9KvEtvWfHALihnMbL8P7VXkk8VijKjDwO4ucEeArltYhvljZg08aJI0sOTy3gwQuHGUpHCHQpssbmLFxYQLz33OMWIEr9N5V/sj16/Om1RhBijYZKb0MSyrcJunpilmXQzWfhNatNSw9BGoQdVJSHVIqmOMe63NAy9dKNlpsy0Y6w69QeU+VOZwSF9Fj/Zt7UW9mzfb/H8mDu5ifyR8ideKxtHC39imRqSc2lOq0ljpl50G/Gfn4TJZqDo22q3HxtpDPVIjBmPlAc4wQYV8N1v8r6WEEVdb8JD0Tq54OiF6k5fOiZYS8I0ZCRg5DAiHOBQ+AZthhbkrrtWNNu/if21zPpiFuHwImeF9N+UC3tCSeDbG5tNWHuqF0SpF4EUZUZ4n0lG1SsmR2IKhheJjWFL/8yHA6FSXiZ9lj24sex90ScvsfzHdmzdyxkW62Y46JEoByQ8KqFi4jJLYVrucgpedtQDR8TgBNf9SkBtu7hCImHyIFDE1CVr3tS+qmKrfALflcaiXhANuyEBwt8tGYX028SyFvuEkoN0m/HW9WvjfL47ZIhW23WdzX7rvayzjfX6ZaSJPCrrXk9bCisBA7McsvSd9T337/PFGcx/QWbUirN3l6xvedQ==
  template:
    metadata:
      creationTimestamp: null
      name: bm-auth-altra
      namespace: tink-system
    type: kubernetes.io/basic-auth
