---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdi-manifests
spec:
  destination:
    namespace: cdi
    server: https://192.168.56.151:6443
  project: default
  source:
    path: config/workload/cdi
    repoURL: git@github.com:cloudbase/BMK.git
    targetRevision: cncf_tm_baremetal_kvm
