---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: nginx
    server: https://192.168.56.151:6443
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: config/workload/nginx
    repoURL: git@github.com:cloudbase/BMK.git
    targetRevision: cncf_tm_baremetal_kvm
